# Generated by Django 2.2.17 on 2021-01-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsApp', '0003_cardpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpatient',
            name='placeVizit',
            field=models.CharField(max_length=500, verbose_name='Место визита'),
        ),
    ]
